apiVersion: v1
kind: Pod
metadata:
  name: redis-emptydir
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: hostpath-vol
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
  - name: hostpath-vol
    hostPath:
      path: /var/tmp
